server:
  port: 8099
spring:
  #===============Mysql database==================
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.91.2:3306/goddb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&rewriteBatchedStatements=true
    username: eddie
    password: 1003
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    filters: config,stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;
    public-key:

  ############################## redis  ####################################################
  redis:
    database: 0
    host: 100.8.0.98
    port: 6379
    password:
    timeout: 10000

############################## druid datasource  #########################################
druid:
  resetEnable: true
  urlMappings: /druid/*
  loginUsername: admin
  loginPassword: admin
  allow:
  deny:

############################## mybatis conf  #############################################
mybatis:
  mapper-locations: classpath:mapper/*.xml

############################## pagehelper conf  ##########################################
pagehelper:
  helperDialect: mysql
  reasonable: true
  offsetAsPageNum: true
  pageSizeZero: true
  supportMethodsArguments: true
  params: count=countSql;

httpclient:
  #最大连接数
  maxTotal: 1000
  #并发数
  defaultMaxPerRoute: 100
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 5000
